//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyItemStatusValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BodyItemStatusValue">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PASS"/>
 *     &lt;enumeration value="FAIL"/>
 *     &lt;enumeration value="SKIP"/>
 *     &lt;enumeration value="NOT RUN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BodyItemStatusValue")
@XmlEnum
public enum BodyItemStatusValue {

    PASS("PASS"),
    FAIL("FAIL"),
    SKIP("SKIP"),
    @XmlEnumValue("NOT RUN")
    NOT_RUN("NOT RUN");
    private final String value;

    BodyItemStatusValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BodyItemStatusValue fromValue(String v) {
        for (BodyItemStatusValue c: BodyItemStatusValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
