//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import javax.xml.bind.annotation.*;
import java.util.LinkedList;
import java.util.List;


/**
 * <p>Java class for For complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="For">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="var" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="iter" type="{}ForIteration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kw" type="{}Keyword" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="msg" type="{}Message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="doc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{}BodyItemStatus"/>
 *       &lt;/choice>
 *       &lt;attribute name="flavor" type="{}ForFlavor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "For")
public class For extends OutputElement {

    @XmlElements({
            @XmlElement(name = "iter", type = ForIteration.class, required = false),
            @XmlElement(name = "kw", type = Keyword.class, required = false)
    })
    protected List<OutputElement> keywordOrIter = new LinkedList<>();

    @XmlElement(name = "var", type = String.class)
    protected List<String> vars;
    @XmlElement(name = "msg", type = Message.class)
    protected List<Message> msg;
    @XmlElement(name = "doc", type = String.class)
    protected String doc;
    @XmlElement(name = "status", type = BodyItemStatus.class)
    protected BodyItemStatus status;
    @XmlElement(name = "value", type = String.class)
    protected String value;

    @XmlAttribute(name = "flavor")
    protected ForFlavor flavor;

    @Override
    public String getName() {
        return "FOR";
    }

    @Override
    public List<OutputElement> getElements() {
        return keywordOrIter;
    }

    public List<OutputElement> getKeywordOrIter() {
        return keywordOrIter;
    }

    public List<String> getVars() {
        return vars;
    }

    public List<Message> getMsg() {
        return msg;
    }

    public String getDoc() {
        return doc;
    }

    public BodyItemStatus getStatus() {
        return status;
    }

    public String getValue() {
        return value;
    }

    public ForFlavor getFlavor() {
        return flavor;
    }

    public void setFlavor(ForFlavor value) {
        this.flavor = value;
    }

}
