//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import java.util.LinkedList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IfBranch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IfBranch">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="kw" type="{}Keyword" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="for" type="{}For" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="if" type="{}If" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="return" type="{}Return" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="msg" type="{}Message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="doc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{}BodyItemStatus"/>
 *       &lt;/choice>
 *       &lt;attribute name="type" use="required" type="{}IfType" />
 *       &lt;attribute name="condition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IfBranch")
public class IfBranch extends OutputElement {

    @XmlElements({
        @XmlElement(name = "kw", type = Keyword.class),
        @XmlElement(name = "for", type = For.class),
        @XmlElement(name = "if", type = If.class)
    })
    protected List<OutputElement> kwOrForOrIf = new LinkedList<>();

    @XmlElement(name = "msg", type = String.class)
    protected List<String> msg;
    @XmlElement(name = "doc", type = String.class)
    protected String doc;
    @XmlElement(name = "status", type = BodyItemStatus.class)
    protected BodyItemStatus status;
    @XmlElement(name = "return", type = Return.class)
    protected Return returnn;

    @XmlAttribute(name = "type", required = true)
    protected IfType type;
    @XmlAttribute(name = "condition")
    protected String condition;

    @Override
    public String getName() {
        return "IfBranch";
    }

    @Override
    public List<OutputElement> getElements() {
        return kwOrForOrIf;
    }

    public List<OutputElement> getKwOrForOrIf() {
        return kwOrForOrIf;
    }

    public List<String> getMsg() {
        return msg;
    }

    public String getDoc() {
        return doc;
    }

    public BodyItemStatus getStatus() {
        return status;
    }

    public Return getReturnn() {
        return returnn;
    }

    public IfType getType() {
        return type;
    }

    public void setType(IfType value) {
        this.type = value;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String value) {
        this.condition = value;
    }

}
