//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Suite complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Suite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="kw" type="{}Keyword" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="suite" type="{}Suite" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="test" type="{}Test" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="doc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="meta" type="{}Metadata" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="status" type="{}Status"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suite")
public class OutputSuite extends OutputElement {

    @XmlElement(name = "kw", type = Keyword.class)
    protected List<Keyword> keywords = new LinkedList<>();
    @XmlElement(name = "suite", type = OutputSuite.class)
    protected List<OutputSuite> suites = new LinkedList<>();
    @XmlElement(name = "test", type = Test.class)
    protected List<Test> tests = new LinkedList<>();
    @XmlElement(name = "doc", type = String.class)
    protected String doc;
    @XmlElement(name = "meta", type = Metadata.class)
    protected Metadata meta;
    @XmlElement(name = "status", type = Status.class)
    protected Status status;

    @XmlAttribute(name = "source")
    protected String source;
    @XmlAttribute(name = "id")
    protected String id;

    public List<Keyword> getKeywords() {
        return keywords;
    }

    public List<OutputSuite> getSuites() {
        return suites;
    }

    public List<Test> getTests() {
        return tests;
    }

    public String getDoc() {
        return doc;
    }

    public Metadata getMeta() {
        return meta;
    }

    public Status getStatus() {
        return status;
    }

    @Override
    public List<OutputElement> getElements() {
        LinkedList<OutputElement> result = new LinkedList<>();
        result.addAll(keywords);
        result.addAll(tests);
        result.addAll(suites);
        return result;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String value) {
        this.source = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String value) {
        this.id = value;
    }

}
