//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Robot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Robot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="suite" type="{}Suite"/>
 *         &lt;element name="statistics" type="{}Statistics" minOccurs="0"/>
 *         &lt;element name="errors" type="{}Errors" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="generator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rpa" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="schemaversion" type="{}SpecVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "robot")
@XmlAccessorType(XmlAccessType.FIELD)
public class Robot {

    @XmlElement(required = true)
    protected OutputSuite suite;
    protected Statistics statistics;
    protected Errors errors;
    @XmlAttribute(name = "generator")
    protected String generator;
    @XmlAttribute(name = "generated")
    protected String generated;
    @XmlAttribute(name = "rpa")
    protected Boolean rpa;
    @XmlAttribute(name = "schemaversion")
    protected Integer schemaversion;

    public OutputSuite getSuite() {
        return suite;
    }

    public void setSuite(OutputSuite value) {
        this.suite = value;
    }

    public Statistics getStatistics() {
        return statistics;
    }

    public void setStatistics(Statistics value) {
        this.statistics = value;
    }

    public Errors getErrors() {
        return errors;
    }

    public void setErrors(Errors value) {
        this.errors = value;
    }

    public String getGenerator() {
        return generator;
    }

    public void setGenerator(String value) {
        this.generator = value;
    }

    public String getGenerated() {
        return generated;
    }

    public void setGenerated(String value) {
        this.generated = value;
    }

    public Boolean isRpa() {
        return rpa;
    }

    public void setRpa(Boolean value) {
        this.rpa = value;
    }

    public Integer getSchemaversion() {
        return schemaversion;
    }

    public void setSchemaversion(Integer value) {
        this.schemaversion = value;
    }

}
