//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Statistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="total" type="{}TotalStatistics"/>
 *         &lt;element name="tag" type="{}TagStatistics"/>
 *         &lt;element name="suite" type="{}SuiteStatistics"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Statistics", propOrder = {

})
public class Statistics {

    @XmlElement(required = true)
    protected TotalStatistics total;
    @XmlElement(required = true)
    protected TagStatistics tag;
    @XmlElement(required = true)
    protected SuiteStatistics suite;

    public TotalStatistics getTotal() {
        return total;
    }

    public void setTotal(TotalStatistics value) {
        this.total = value;
    }

    public TagStatistics getTag() {
        return tag;
    }

    public void setTag(TagStatistics value) {
        this.tag = value;
    }

    public SuiteStatistics getSuite() {
        return suite;
    }

    public void setSuite(SuiteStatistics value) {
        this.suite = value;
    }

}
