//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Status complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Status">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="status" use="required" type="{}StatusValue" />
 *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="elapsedtime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Status", propOrder = {
    "value"
})
public class Status {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "status", required = true)
    protected StatusValue status;
    @XmlAttribute(name = "starttime")
    protected String starttime;
    @XmlAttribute(name = "endtime")
    protected String endtime;
    @XmlAttribute(name = "elapsedtime")
    protected String elapsedtime;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public StatusValue getStatus() {
        return status;
    }

    public void setStatus(StatusValue value) {
        this.status = value;
    }

    public String getStarttime() {
        return starttime;
    }

    public void setStarttime(String value) {
        this.starttime = value;
    }

    public String getEndtime() {
        return endtime;
    }

    public void setEndtime(String value) {
        this.endtime = value;
    }

    public String getElapsedtime() {
        return elapsedtime;
    }

    public void setElapsedtime(String value) {
        this.elapsedtime = value;
    }

}
