//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TagStat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagStat">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="pass" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fail" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="skip" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="doc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="links" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="combined" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagStat", propOrder = {
    "value"
})
public class TagStat {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "pass")
    protected BigInteger pass;
    @XmlAttribute(name = "fail")
    protected BigInteger fail;
    @XmlAttribute(name = "skip")
    protected BigInteger skip;
    @XmlAttribute(name = "doc")
    protected String doc;
    @XmlAttribute(name = "links")
    protected String links;
    @XmlAttribute(name = "info")
    protected String info;
    @XmlAttribute(name = "combined")
    protected String combined;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public BigInteger getPass() {
        return pass;
    }

    public void setPass(BigInteger value) {
        this.pass = value;
    }

    public BigInteger getFail() {
        return fail;
    }

    public void setFail(BigInteger value) {
        this.fail = value;
    }

    public BigInteger getSkip() {
        return skip;
    }

    public void setSkip(BigInteger value) {
        this.skip = value;
    }

    public String getDoc() {
        return doc;
    }

    public void setDoc(String value) {
        this.doc = value;
    }

    public String getLinks() {
        return links;
    }

    public void setLinks(String value) {
        this.links = value;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String value) {
        this.info = value;
    }

    public String getCombined() {
        return combined;
    }

    public void setCombined(String value) {
        this.combined = value;
    }

}
