//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.16 at 04:23:27 PM CET 
//


package org.robotframework.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TotalStat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TotalStat">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="pass" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fail" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="skip" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalStat", propOrder = {
    "value"
})
public class TotalStat {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "pass")
    protected BigInteger pass;
    @XmlAttribute(name = "fail")
    protected BigInteger fail;
    @XmlAttribute(name = "skip")
    protected BigInteger skip;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public BigInteger getPass() {
        return pass;
    }

    public void setPass(BigInteger value) {
        this.pass = value;
    }

    public BigInteger getFail() {
        return fail;
    }

    public void setFail(BigInteger value) {
        this.fail = value;
    }

    public BigInteger getSkip() {
        return skip;
    }

    public void setSkip(BigInteger value) {
        this.skip = value;
    }

}
